### PR TITLE
Do not include default query params in href

### PR DESCRIPTION
**Pull request by garronej**
Implements https://github.com/zilch/type-route/issues/137

### CODE REVIEW

**Comment by bradenhs** [comment]
Code look great! I tested it out and everything works as expected! Thanks for the contribution!

Once CI passes I'll merge and release a new Type Route version today.

**Comment by bradenhs** [comment]
Huh... CI is still stuck. I might need to update the github action. I ran tests locally though and everything looks good. I'll merge this now and get CI fixed then deploy (maybe early next week).

**Comment by garronej** [comment]
Thank you for reviewing and merging!  

> The code looks great! I tested it out and everything works as expected! Thanks for the contribution!  

No problem, the code is very well organized so it went very somothly!  

> Huh... CI is still stuck. I might need to update the github action.  

I saw you're using tsdx... I'm quite reseved about this project. In particular because it bundles all the code into a single file which it not how npm module should be distributed.  

Anyway, I'm very happy this feature is now part of type-route.  

And by the way, I don't know if I told you but I recomend `type-route` in the documentation for building french public services websites with React:  

https://react-dsfr.codegouv.studio/routing  

Note that I recomend to use type-route instead of react-router.  

As a result some important project are being build with type route such as this one:  

https://www.linkedin.com/feed/update/urn:li:activity:7131185504712028160?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7131185504712028160%29

**Comment by bradenhs** [comment]
So happy to hear about different places where Type Route is being used and appreciated! Thank you for sharing. On the subject of `tsdx` I'd be happy to explore migrating to a different solution sometime, but it won't be a priority of mine in the near future. I've also been less keen about `tsdx` lately and wouldn't start a new project using it.

**Comment by garronej** [comment]
Of course, I'm not sugesting you migrate, it wouldn't be worth the effort. I was just mentioning it casually.  
If you want to explore other options you might want to chechout my starter https://github.com/garronej/ts-ci.  
I had to create one for my own modules.

**Comment by bradenhs** [comment]
Nice! I'll check it out.

**Pull request merged**
